### ISSUE TITLE
TypeScript with "moduleResolution": "bundler" can't import the npm package 

### ISSUE THREAD

**Issue by Iverson** [Vyro-ai/imagine-sdk-js#1]
**Steps to reproduce**
1. Create a TypeScript project with `"moduleResolution": "bundler"`
2. `yarn install imaginesdk` or `npm install imaginesdk`
3. Try to import `import { client } from 'imaginesdk'`

**Expected behavior**
`imaginesdk` module should be imported with all type definitions

**Actual behavior**
TypeScript build throws an error `ERROR(TypeScript)  Cannot find module 'imaginesdk' or its corresponding type declarations.`

**Additional context**
Node.js - v18.18.0
TypeScript - v5.2.2
Vite - v4.4.11

**Comment by m-shariq** [comment]
Hey @Iverson, we couldn't reproduce the error, can you please share the sample codebase?

**Comment by Iverson** [comment]
> Hey @Iverson, we couldn't reproduce the error, can you please share the sample codebase?

Hey @m-shariq , I prepared a repo:

https://github.com/Iverson/imagine-sdk-issue/tree/main - branch with the released version of `imaginesdk`
https://github.com/Iverson/imagine-sdk-issue/tree/fix - branch that uses a version with my fix of `imaginesdk`

Just run these commands to test the build
```
yarn
yarn dev
```
